### ISSUE TITLE
we should not default to any iamge form the redhat regeistry as the operators shoudl be deployable without a pull secret

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/openstack-operator#235]
https://github.com/openstack-k8s-operators/openstack-operator/blob/be3d3c851b83ce01e7f0f4cf8a9bf13e764901f1/pkg/openstack/rabbitmq.go#L81

we shoudl not be defaulting to images form the redhat registry for any service images

they should be using the image from tripleo/tcib/quay

this should be using quay.io/tripleozedcentos9/openstack-rabbitmq:current-tripleo

until we swap to using the new tcib images.

**Comment by SeanMooney** [comment]
the new tcib image is here
quay.io/podified-zed-centos9/openstack-rabbitmq:current-podified

**Comment by dprince** [comment]
I have actually brought up the idea that we do *a lot* more of this. As this is mostly a RH project ATM and we only use OpenShift one could take the position that a pull secret is a fine requirement.

That said I'm open to using a new container image for rabbit assuming it matches the downstream requirements (interfaces). @jeckersb is there such an image?

In the meantime, this project isn't tracking things in github issues/aside from Renovatebot. So going to close this and we can follow up with a Jira.
