### ISSUE TITLE
Deployment Instructions - Problems with config/samples 

### ISSUE THREAD

**Issue by akyriako** [openstack-k8s-operators/openstack-operator#331]
Hi there, awesome work! Are there any end-to-end installation instructions in place (besides the generic README from the operator sdk for each project)? 

I try to install the operators for each service and many of them are failing when I apply the config/samples as required fields are missing from the yaml files.

Any help would be appreciated. Thank you in advance.

**Comment by abays** [comment]
The intended use of the various operators is through this operator (OpenStack operator) and its `OpenStackControlPlane` CRD.  We call this operator the "umbrella" operator that encompasses all the OpenStack service operators.  Deploying each service operator individually is not an intended use case, nor is really applying individual CRs for those operators.  Instead, you should use a sample like [1] to deploy an OpenStack control plane.  You can modify the YAML blocks for the various OpenStack services and set `enabled: false` for those you do not wish to deploy.

If you want a more automated approach, we use `install_yamls` [2] to handle both the deployment of the OpenStack operator itself and then also to apply an `OpenStackControlPlane` CR to the cluster.  A basic quickstart would be as follows:

```
git clone https://github.com/openstack-k8s-operators/install_yamls.git

# BEGIN: If you don't already have an OpenShift cluster, you can do the following...
# copy pull-secret.txt (you must acquire this from https://console.redhat.com/openshift/create/local) to install_yamls/devsetup
cd install_yamls/devsetup
make download_tools
CPUS=12 MEMORY=25600 DISK=100 make crc
eval $(crc oc-env)
oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443/
cd ..
make crc_storage
# END: Create OpenShift cluster

# Install the OpenStack operator (which will then also install all the individual OpenStack service operators)
make openstack

# Deploy the OpenStack services via an OpenStackControlPlane CR
make openstack_deploy
```

I hope this helps getting you started.

[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/main/config/samples/core_v1beta1_openstackcontrolplane.yaml
[2] https://github.com/openstack-k8s-operators/install_yamls
