### ISSUE TITLE
Schema validation for OpenStackControlPlane input

### ISSUE THREAD

**Issue by rszmigiel** [openstack-k8s-operators/openstack-operator#540]
I made an attempt to install control plane using DP1 configuration file while using DP2. It was successful however it used the defaults instead of my config. The obvious reason is I've used DP1 config file against DP2 deployment. The less obvious thing is that it worked without any warning or error.

 Therefore could we get implemented input validation?

**Comment by dprince** [comment]
We have some basic input validations today that are implemented via validating webhooks. The openstack operator should always execute the validation webhooks for each of the service operators as implemented by our framework.

**Comment by dprince** [comment]
Most of the input validations are to make sure that things like the containerImages are actually set to something. But in addition to the validations we also have "defaulting" webhooks enabled as well, and the images get defaulted for example automatically. I think the it just works unless you need to override, or customize something is how we intend things to work.
