### ISSUE TITLE
How do we install the CRDs of each service from the umbrella controller?

### ISSUE THREAD

**Issue by akyriako** [openstack-k8s-operators/openstack-operator#575]
I try to install openstack from the umbrella controller but I get the same error for every service from the reconciliation loop:

**if kind is a CRD, it should be installed before calling Start","kind":"KeystoneAPI.keystone.openstack.org**

![image](https://github.com/openstack-k8s-operators/openstack-operator/assets/3920167/a54bbd66-8b1e-4460-97ac-487ad8f01ca3)

**Comment by akyriako** [comment]
Thanks for your reply. But what if I want to go via **make deploy** or **make run** or even debug directly the source code if I have made some changes to the controllers?

**Comment by dprince** [comment]
CRDs are installed via OLM (Operator Lifecycle Manager) using operator dependencies: https://github.com/openstack-k8s-operators/openstack-operator/blob/main/dependencies.yaml
