### ISSUE TITLE
[question] how to change container image url?

### ISSUE THREAD

**Issue by angry-tony** [openstack-k8s-operators/openstack-operator#878]
hello, guys..

Is there a way to configure it in a disconnected environment?

Do I need to manually find the value that refers to the image in each operator and change the existing value to an internal registry that is not connected to the Internet?
`FROM
containerImage: quay.io/podified-antelope-centos9/openstack-ovn-nb-db-server:current-podified
TO
containerImage: local.registry/CUSTOM_NAMESPACE/openstack-ovn-nb-db-server:CUSTOM_TAG`

Is there any easy way or document I can refer to?

**Comment by abays** [comment]
You can pre-create an `OpenStackVersion` CR to change OSP service images.  See [1] for an example and [2] for reference.

[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/main/config/samples/core_v1beta1_openstackversion.yaml
[2] https://github.com/openstack-k8s-operators/openstack-operator/blob/d23dd170dd2a93298bd6283bb20aade1817e8d50/apis/core/v1beta1/openstackversion_types.go#L69-L148

**Comment by angry-tony** [comment]
@abays, wow..
thank you!!
i will try it.

**Comment by dprince** [comment]
Abays answer is correct however one clarification would be that doing this is considered to be an override or "hotfix" for the container images. When you override things in this manner it is then your responsibility to maintain those images for future updates. Additionally, when a "minor update" is triggered you would need to bump each of these images when a new targetVersion is set on the OpenStackVersion resource. In short, it really isn't ideal to rely on this interface as a means to support disconnected environments.

Instead use the standard OpenShift interface for offline/disconnected environments: https://docs.openshift.com/container-platform/4.16/installing/disconnected_install/installing-mirroring-installation-images.html#installing-mirroring-installation-images

Our operator bundles have the necissary RELATED_IMAGE settings in them to be able to mirror the required images into the configured private registry. Then you would be able to transparently consume those images, and ultimately leverage the normal minor updates workflow with the product.

**Comment by angry-tony** [comment]
Oh, it looks like your advice was correct.
I was deciding that it would be difficult for me to build and maintain the image every time.
Thank you very much for providing a good solution.
